### PR TITLE
Implemented automatic template generation for simple exercises

### PR DESCRIPTION
**Pull request by jahdiel4j**
# Description

Added two new dependencies, jszip and file-saver.
Added a new file (TemplateGeneration.tsx).
Added a new button in ModuleAccordion.tsx.
Routed button to new TemplateGenerator function in the new file.
Template Generator function calls API for problem data, then calls generators for each file in template.
Resulting template content is zipped and provided to client.

# Related Issue

Automatic template generation.

# Motivation and Context

This feature provides an optimization for the process of administrators creating template folders for coding problems.

# How Has This Been Tested?

Ran existing tests to verify this new feature does not break existing implementation.
Ran the feature on all existing problems in development mode.

# Screenshots (if appropriate):
image

### CODE REVIEW

**Comment by kapooramanpreet** [comment]
Can you look at the CI test Jahdiel?

**Comment by jahdiel4j** [comment]
> k

Should be good now, was facing some lint issues.

**Comment by kapooramanpreet** [comment]
Thanks. Can we decouple catch.hpp code (Catch framework code from TemplateGeneration.tsx? It will be best to decouple it for better maintenance?

**Comment by jahdiel4j** [comment]
> Thanks. Can we decouple catch.hpp code (Catch framework code from TemplateGeneration.tsx?

Absolutely. I can decouple it and keep it within the same folder as TemplateGeneration.tsx. Or, I can place it in src/assets if you think that is better.

**Comment by kapooramanpreet** [comment]
Move it to assets. Thanks

**Review by kapooramanpreet — APPROVED** [review]
LGTM.

**Pull request closed without merging**
