### PR TITLE
Adrian salazar/grading requests

### PR DESCRIPTION
**Pull request by AqSlz**
What does this PR do?

- This Pull Request adds the ability to send grading requests to the backend
- This Pull Request adds validation to the email textfield in the dialog
- This Pull Request adds a progress bar to the upload, but uploads are too fast so far to appreciate it

The relevant files are currently under the `src/pages/grading` folder.

In `src/pages/grading` you can find

- `GradingDialog.slice.ts ` is for managing the redux state. It has a feedback variable and the upload state
- `GradingDialog.sagas.ts` for sending the grading request to the backend and listening for progress on the upload.

---
Here is a .gif of the dialog when in-use.

Grading Dialog 11-02-2021

Edit: Need to use smaller screen when doing a .gif

Click .gif to see it in a larger size, for better quality

---
I need to set up testing, in a future PR. 

I want to be able to mock user input from Jest, so far I can only mock sending a request and getting the "OK"

### CODE REVIEW

**Review by marcgabe15 — DISMISSED** [review]
This looks awesome! It's super cool that you were able to set up drag and drop natively without using an npm package and all the error messages and feedbacks look great!

**Comment by AqSlz** [comment]
Thank you

**Review by tanner-ropp — DISMISSED** [review]
LGTM!

**Review by tanner-ropp — APPROVED** [review]
LGTM

**Review by marcgabe15 — APPROVED** [review]

**Pull request merged**
