### PR TITLE
Tanner ropp/problem editor back to modules

### PR DESCRIPTION
**Pull request by tanner-ropp**
# What does this PR do?
I added a back button to the problem editor in case you need to navigate back to modules without submitting changes.  I also added spacing between multiple buttons in the `LayoutContainer`.
Screen Shot 2021-11-16 at 5 38 03 PM

### CODE REVIEW

**Review by marcgabe15 — APPROVED** [review]
Looks great!

**Comment by AqSlz** [comment]
Sometimes changing the variants for different emphasis for each of the buttons results in better design, I suggest you test that and see if you like better the "Back to modules" button when it is an outlined variant, or some other variant.

**Comment by tanner-ropp** [comment]
> Sometimes changing the variants for different emphasis for each of the buttons results in better design, I suggest you test that and see if you like better the "Back to modules" button when it is an outlined variant, or some other variant.

I'll try outlined

**Comment by tanner-ropp** [comment]
> Sometimes changing the variants for different emphasis for each of the buttons results in better design, I suggest you test that and see if you like better the "Back to modules" button when it is an outlined variant, or some other variant.

Thoughts on this @AqSlz ?

Screen Shot 2021-11-16 at 8 47 23 PM

**Comment by AqSlz** [comment]
> Thoughts on this @AqSlz ?

I like it, there is different emphasis. This is also fine. I can approve right now if you plan on adding that to a future PR.

**Review by AqSlz — APPROVED** [review]

**Comment by tanner-ropp** [comment]
> > Thoughts on this @AqSlz ?
> 
> I like it, there is different emphasis. This is also fine. I can approve right now if you plan on adding that to a future PR.
> 
> Edit: Just realized that you already committed the changes @tanner-ropp

thanks!

**Review by marcgabe15 — APPROVED** [review]

**Pull request merged**
